# Generated by Django 5.2.8 on 2026-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trfsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('livree', 'Livrée')], default='en_attente', max_length=20),
        ),
    ]
