# Generated by Django 5.2.8 on 2026-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trfsApp', '0002_alter_commande_reference_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_expedition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='estimation_cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='lieu_depart',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='poids_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_marchandise',
            field=models.CharField(blank=True, choices=[('colis', 'Colis'), ('document', 'Document'), ('fragile', 'Fragile'), ('industriel', 'Industriel'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='destination',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('en_cours', 'En cours'), ('livree', 'Livrée')], default='en_attente', max_length=20),
        ),
    ]
